### ISSUE TITLE
Doesn't get all output, notably error (master)

### ISSUE THREAD

**Issue by Unactived** [teward/pytio#2] opened 2018-10-18 05:56 UTC
See the following example
Tio.run does show an error
```python
>>> from pytio import Tio
>>> site = Tio()
>>> code = """print("text1")
... print("text2")
... print(undefined_thing)"""
>>> req = site.new_request('python3', code)
>>> res = site.send(req)
>>> print(res.error)
None
>>> print(res.result)
text1
text2

>>>```

**Comment by teward** [comment] 2018-10-19 19:59
I can confirm that this is an issue.  This is because of how we handle getting the result data at https://github.com/teward/pytio/blob/master/pytio/_TioResult.py#L32

Let me look into fixing this.

**Comment by teward** [comment] 2018-10-19 20:02
Relevant: This is your example in TIO itself:

https://tio.run/##K6gsycjPM/7/v6AoM69EQ6kktaLEUEmTC4lrBOeW5qWkpmXmpabEl2Rk5qVr/v8PAA

As you can see, the 'output' section is what the 'result' is, and it doesn't do 'error' properly.  Let me see if I can't fix that...

**Comment by Unactived** [comment] 2018-10-19 20:16
Using more or less what was answered in your related [code review](https://codereview.stackexchange.com/questions/182399/python-library-for-tio-run-interaction), it seems that every form of output given (both program's output and errors) is gathered in TioResponse.result, always leaving TioResponse.error None.
Though depending of languages, they cannot get properly separated.

**Comment by Unactived** [comment] 2018-10-19 20:18
More precisely, Output and Debug version gets together concatenated (in that order) into response.result.
This is why the time, RAM used etc. will always be in result : it's from Debug

**Comment by teward** [comment] 2018-10-19 20:19
indeed, looking at this again you are correct.  Closing.

**Closed as completed by teward** 2018-10-19 20:19 UTC

**Comment by teward** [comment] 2018-10-19 20:30
Also note, the use of `new_request` is not supported anymore.  It has been removed from the latest bit of the code.  You would make a Tio Site and Request as follows:

```
from tio import Tio, TioRequest

site = Tio()
code = "print('This is Test Code!')"
req = TioRequest("python3", code)
res = site.send(req)
# Do something with result data.
```

`new_request` was a holdover from the original Java library until I created the `TioRequest` object's constructor.

**Comment by Unactived** [comment] 2018-10-19 20:32
Yes I saw the DeprecationWarning in the code and was already using TioRequest constructor directly.

**Comment by teward** [comment] 2018-10-19 20:34
@FrenchMasterSword good to know.  I've yanked the `new_request` function out entirely now though so just wanted to make sure :)
